feat, #272: Add support for spi-mode in cmdline.
rm-hull/luma.core pull request #273
Opened 2024-01-21 14:40 UTC by AlessioMorale

This pr add support '--spi-mode' command line option,  #272

2024-01-21 18:17 UTC, thijstriemstra commented
thanks! Looks like the tests are failing due to #274. Once that's merged I'll take a look at this.

2024-01-21 18:56 UTC, thijstriemstra requested changes
Tests also ned to be adjusted since they're failing: https://github.com/rm-hull/luma.core/actions/runs/7603076282/job/20704367265?pr=273

2024-01-22 00:51 UTC, AlessioMorale commented
thanks! Tests should now be fine

2024-01-24 17:14 UTC, thijstriemstra approved these changes

2024-01-24 17:15 UTC, merged